# Generated by Django 4.1.2 on 2022-10-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_store", "0006_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
