# Generated by Django 4.1.2 on 2022-10-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_store", "0007_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
